language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28

  licenses:
    - 'android-sdk-license-.+'
    - 'android-preview-sdk-license-.+'
    - '-.+'

script:
  - ./gradlew check
  - ./gradlew desktop:build
  - ./gradlew android:build

cache:
  directories:
    - $HOME/.android

branches:
  only:
    - master
    - /^rel-.*$/

before_install:
  - mkdir -p "$ANDROID_HOME/licenses"
  - echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - yes | sdkmanager --licenses

addons:
  artifacts: true

#addons:
#  artifacts:
#    paths:
#      - bin/*-debug.apk
#      - ./*.jar
